### PR TITLE
A bit of cleanup and deprecation fixes

### PR DESCRIPTION
**Pull request by TacoTheDank**
The code is super snarky, I'm a big fan lol.

#### 1st commit
- Delete the autogenerated .iml files (adding them to .gitignore)

#### 2nd commit
- Fix the AS deprecation from 4.0 (https://github.com/YTVanced/VancedManager/commit/d49374020a06de90f617ca00326d2987fbc185a9)

#### 3rd commit
- Organize libraries (and bumping Kotlin to JDK8)

#### 4th commit
- Delete unused (and deprecated) AndroidX legacy library
- Replace deprecated lifecycle-extensions ([context](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.2.0))

#### 5th commit
- Delete unused exo_thin font
- Update exo_bold font from (https://fonts.google.com/specimen/Exo)

#### 6th commit
- Added localbroadcastmanager to fix unresolving errors
- Some tiny cleanup

### CODE REVIEW

**Comment by X1nto** [comment]
Oh god, I was using jdk7 the whole time 🤦. Thanks for your effort, we highly appreciate it

**Comment by KevinX8** [comment]
Real question is did it solve the frozen splash screen lol

**Comment by TacoTheDank** [comment]
No problem :P

**Comment by TacoTheDank** [comment]
Oh god I made the pull request to the master branch. 🤦  Sorry bout that.

**Comment by KevinX8** [comment]
That's ok, it should have been more clear which was the working branch, I've cleaned it up now

**Pull request merged**
