### PR TITLE
Beautify Readme

### PR DESCRIPTION
**Pull request by sudo-nautilus**
Title says it all

### CODE REVIEW

**Comment by sudo-nautilus** [comment]
This includes center aligned heading and new badges

**Comment by X1nto** [comment]
Center alignment doesn't really look good when it comes to readmes

**Comment by sudo-nautilus** [comment]
> Center alignment doesn't really look good when it comes to readmes

Expected that,
I'll change it now

**Comment by X1nto** [comment]
Could you re-add square badges and the "get it on google play" badge? those looked great

**Comment by sudo-nautilus** [comment]
> Could you re-add square badges and the "get it on google play" badge? those looked great

Done

**Comment by X1nto** [comment]
looks great

**Comment by sudo-nautilus** [comment]
Thanks

**Pull request merged**
