### PR TITLE
Optimize assets.

### PR DESCRIPTION
**Pull request by K0-RR**
Lossless compression.

### CODE REVIEW

**Review by sudo-nautilus — APPROVED** [review]
Looks great btw :trollface:

**Comment by sudo-nautilus** [comment]
@RDKRACZ how you did that by the way

**Comment by agret** [comment]
> @RDKRACZ how you did that by the way

They probably ran it through pngcrush

https://pmt.sourceforge.io/pngcrush/

**Comment by sudo-nautilus** [comment]
> > @RDKRACZ how you did that by the way
> 
> They probably ran it through pngcrush
> 
> https://pmt.sourceforge.io/pngcrush/

Hmm, interesting

**Comment by K0-RR** [comment]
I used oxipng for this (it's better than pngcrush or optipng)
https://github.com/shssoichiro/oxipng
`oxipng -o max -s full -r --fix -t 8 -Z`

**Comment by sudo-nautilus** [comment]
Oh ok

**Pull request merged**
