### PR TITLE
initial translation

### PR DESCRIPTION
**Pull request by Gozzwip**
Azerbaijani (Azərbaycanca) translation

### CODE REVIEW

**Comment by KevinX8** [comment]
please read the readme next time and use crowdin

**Comment by Gozzwip** [comment]
I was informed by Telegram admin

**Comment by Gozzwip** [comment]
Will the translation be added to crowdin? So I can keep working on it there

**Comment by KevinX8** [comment]
yeah I uploaded it for you

**Comment by Gozzwip** [comment]
Thanks

**Pull request closed without merging**
