### PR TITLE
Adjust layout margin

### PR DESCRIPTION
**Pull request by AioiLight**
Proper margins make great looking, and prevent miss touch.

Before | this PR
image
image

### CODE REVIEW

**Comment by X1nto** [comment]
In my opinion app looks a bit uglier with this adjustment, @KevinX8 what do you think

**Comment by KevinX8** [comment]
The home page doesn't look too great yeah, and the update center it's hard to say which is better there

**Comment by AioiLight** [comment]
Is the problem that there is too much space between the lines?

With the previous placement of the logo, I thought it was a bit tight.

**Comment by KevinX8** [comment]
> Is the problem that there is too much space between the lines?
> 
> With the previous placement of the logo, I thought it was a bit tight.

I think the spacing between installed and latest looked better originally.

**Comment by X1nto** [comment]
I think it would be better if buttons were at the edge of card, having a symmetrical distance from top and right edges, as seen in current version of manager. In update center buttons look way out of their place, having them in the middle does not look great for such dialogs

**Comment by AioiLight** [comment]
If you don't like it, then close the PR :D

However, the previous blanks are too tight, so some sort of adjustment may be necessary

**Comment by X1nto** [comment]
We might increase margin size a bit, but not too much. Thanks for advise

**Pull request closed without merging**
