### PR TITLE
improvement -> Styling home ui components

### PR DESCRIPTION
**Pull request by HaliksaR**
Icon pack
https://www.figma.com/file/joUVdyTHyrRLQPjAwhnfrM/Material-Icons-(Outlined)-(Copy)?node-id=5%3A0&viewport=1677%2C77%2C1.1502535343170166
image
photo_2020-11-15_23-11-05

### CODE REVIEW

**Comment by X1nto** [comment]
Social buttons and sponsors look less symmetrical imo and outlined buttons don't really fit into the atmosphere here, will probably have to ask others about that

**Comment by HaliksaR** [comment]
> Social buttons and sponsors look less symmetrical imo and outlined buttons don't really fit into the atmosphere here, will probably have to ask others about that

Ok, waiting others

**Comment by HaliksaR** [comment]
rebase dev

**Comment by KevinX8** [comment]
I think the best approach would be to just force landscape mode to either have 4 across or 8 across and never anything in between (other than 2 I guess?). Making it left-aligned looks very strange especially in landscape mode.

**Pull request closed without merging**
